services:

  frontend-service:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend-service

  backend-service:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres-service
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: angelcorp
      DB_USER: angel
      DB_PASSWORD: angel123

  postgres-service:
    image: postgres:17
    container_name: postgres
    restart: always
    environment:
      POSTGRES_DB: angelcorp
      POSTGRES_USER: angel
      POSTGRES_PASSWORD: angel123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: